name: Simple CI

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master", "develop" ]

jobs:
  build-test-artifact:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.11.0
      uses: actions/setup-node@v4
      with:
        node-version: '20.11.0'
        cache: 'npm' # Utilise le cache npm

    - name: Install dependencies
      # Utilise --legacy-peer-deps si nécessaire en raison de conflits (comme avec TypeDoc/TypeScript)
      run: npm ci --legacy-peer-deps

    - name: Build
      run: npm run build

    - name: Run unit tests with coverage
      run: npm run test:coverage

    - name: Run BDD tests
      run: npm run test:report

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-and-test-results
        path: |
          dist/
          coverage/
          cucumber-report.json
